=== Flexberry/NewPlatform.Flexberry.CodeReviewEngine/ASP.NET/Xml/WebControlProvider.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
// <auto-generated>
//     Внимание! Любые изменения в этом коде являются грубым нарушением 
//     конвенции о взаимодействии с технологическим отделом.
//     Если у вас возникает необходимость в изменении или доработках,
//     обращайтесь в технологический отдел согласно правилам:
//     http://storm:2010/page/TechnoAlgorythm.aspx
//     Все несанкционированные изменения будут удалены 
//     при очередном обновлении технологического слоя.
// </auto-generated>
-->
  <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="propertytype" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:all>
              <xs:element name="control" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="typename" type="xs:string" use="required" />
                  <xs:attribute name="property" type="xs:string" use="required" />
                  <xs:attribute name="codefile" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="editcontrol" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="typename" type="xs:string" use="required" />
                  <xs:attribute name="property" type="xs:string" />
                  <xs:attribute name="codefile" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="filtercontrol" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="typename" type="xs:string" use="required" />
                  <xs:attribute name="codefile" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:all>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="customproperty" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="control" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="typename" type="xs:string" use="required" />
                  <xs:attribute name="property" type="xs:string" use="required" />
                  <xs:attribute name="codefile" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="editcontrol" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="typename" type="xs:string" use="required" />
                  <xs:attribute name="property" type="xs:string" />
                  <xs:attribute name="codefile" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="class" type="xs:string" use="required" />
            <xs:attribute name="property" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Flexberry/NewPlatform.Flexberry.CodeReviewEngine/ASP.NET/Xml/WebControlProvider.xml
<?xml version="1.0" encoding="utf-8" ?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="WebControlProvider.xsd">
  <propertytype name="Boolean">
    <control typename="System.Web.UI.WebControls.CheckBox, System.Web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" property="Checked" codefile=""/>
  </propertytype>
  <propertytype name="Int32">
    <editcontrol typename="ICSSoft.STORMNET.Web.AjaxControls.AlphaNumericTextBox, ICSSoft.STORMNET.Web.AjaxControls" property="Text" codefile="" />
  </propertytype>
  <propertytype name ="NullableInt">
    <editcontrol typename="ICSSoft.STORMNET.Web.AjaxControls.AlphaNumericTextBox, ICSSoft.STORMNET.Web.AjaxControls" property="Text" codefile="" />
  </propertytype>
  <propertytype name ="Int32?">
    <editcontrol typename="ICSSoft.STORMNET.Web.AjaxControls.AlphaNumericTextBox, ICSSoft.STORMNET.Web.AjaxControls" property="Text" codefile="" />
  </propertytype>
  <propertytype name="NullableDateTime">
    <control typename="ICSSoft.STORMNET.Web.AjaxControls.FormattedDateTimeControl" property="Text" codefile=""/>
    <editcontrol typename="ICSSoft.STORMNET.Web.AjaxControls.DatePicker" property="Text" codefile=""/>
  </propertytype>
  <propertytype name="DateTime">
    <control typename="ICSSoft.STORMNET.Web.AjaxControls.FormattedDateTimeControl" property="Text" codefile=""/>
    <editcontrol typename="ICSSoft.STORMNET.Web.AjaxControls.DatePicker" property="Text" codefile=""/>
  </propertytype>
  <propertytype name="DateTime?">
    <control typename="ICSSoft.STORMNET.Web.AjaxControls.FormattedDateTimeControl" property="Text" codefile=""/>
    <editcontrol typename="ICSSoft.STORMNET.Web.AjaxControls.DatePicker" property="Text" codefile=""/>
  </propertytype>
  <propertytype name="Contact">
    <control typename="ICSSoft.STORMNET.Web.AjaxControls.ContactControl, ICSSoft.STORMNET.Web.AjaxControls, Version=1.0.4805.31119, Culture=neutral, PublicKeyToken=null" property="Text" codefile=""/>
  </propertytype>
  <propertytype name="Event">
    <control typename="ICSSoft.STORMNET.Web.AjaxControls.EventControl, ICSSoft.STORMNET.Web.AjaxControls, Version=1.0.4805.31119, Culture=neutral, PublicKeyToken=null" property="Text" codefile=""/>
  </propertytype>
</root>
